Goorm-OGJG/PBL-Instagram-FE

- src/App.tsx
- src/pages/EditProfile/EditProfile.tsx
- src/pages/Feed/Feed.tsx
- src/pages/FindPassword/FindPassword.tsx
- src/pages/Home/Home.tsx
- src/pages/Login/Login.tsx
- src/pages/Profile/Profile.tsx
- src/pages/SavedProfile/SavedProfile.tsx
- src/pages/SearchTag/SearchTag.tsx
- src/pages/SignUp/SignUp.tsx
- src/pages/Story/Story.tsx
> ✨ Feat: 페이지 라우팅 구현 완료

- src/components/SearchInput/SearchInput.tsx
- src/components/Searchbar/Searchbar.tsx
- src/hooks/useHashTag.tsx
- src/pages/Home/components/CommentContent/CommentContent.style.tsx
- src/pages/Home/components/CommentContent/CommentContent.tsx
- src/pages/Home/components/FeedModal/FeedModal.tsx
- src/pages/Home/components/FeedModal/Feedmodal.style.tsx
> ✨ Feat: 피드 모달 삭제 기능 구현 해시태그 로직 변경

- src/api/useUserAPI.ts
- src/pages/FindPassword/FindPassword.tsx
- src/pages/Login/Login.tsx
- src/pages/SetPassword/SetPassword.tsx
- src/pages/SignUp/SignUp.tsx
- src/types/request/user.request.ts
백엔드 관례를 따르기 위한 변수명 변경
Fixes: #7 #8 #9 #17
> 🚑 Fix: userName -> username 변수명 변경

- src/api/useUserAPI.ts
- src/components/SideMenu/SideMenu.tsx
- tsconfig.json
AccessToken 저장 시 변수명 에러
closed: #53
> 🚑 Fix: 로그인 및 로그아웃 버그 해결

- src/api/useUserAPI.ts
> ✨ Feat: 이메일 검증 기능 임시 삭제

- index.html
index.html 파일에
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"> 추가
> 🚑 Fix: Mixed content 임시 조치

- src/api/useAxios.ts
- src/api/useUserAPI.ts
Authorization -> authorization
fixes: #7
> 🚑 Fix: AccessToken 에러 해결

- src/components/InputBox/InputBox.tsx
- src/pages/Login/Login.tsx
아이디 입력, 비밀번호 컴포넌트에서 Enter키를 keyUp 하면
로그린 요청 전송
fixes: #7
> ✨ Feat: 로그인 버튼 - Enter키를 keyup 하면 동작

- src/api/useAxios.ts
토큰 재발급 요청을 반환하도록 설정
closed: #69
> 🚑 Fix: AccessToken 재발급 후 원본 요청 다시 보내면 에러 해결

- src/api/useEditProfileAPI.ts
- src/api/useFeedAPI.ts
- src/api/useFollowAPI.ts
- src/api/useProfileAPI.ts
- src/api/useSearchAPI.ts
- src/api/useStoryAPI.ts
- src/components/AddModal/AddModal.tsx
- src/hooks/useFileManage.tsx
- src/pages/EditProfile/EditProfile.tsx
- src/pages/Home/components/CommentContent/CommentContent.tsx
- src/pages/Home/components/Feed/Feed.tsx
- src/pages/Home/components/FeedInput/FeedInput.tsx
- src/pages/Home/components/FeedMenu/FeedMenu.tsx
- src/pages/Home/components/Feeds/Feeds.tsx
- src/pages/Home/components/InnerCommentContent/InnerCommentContent.tsx
- src/pages/Home/components/Story/Story.tsx
- src/pages/Profile/Profile.style.tsx
- src/pages/Profile/Profile.tsx
- src/pages/Profile/components/FollowerModal.tsx
- src/pages/Profile/components/ProfileHeader.tsx
- src/pages/Story/Story.tsx
- src/pages/Story/components/Progress/Progress.tsx
- src/pages/Story/components/StoryContent/StoryContent.tsx
- src/pages/Story/components/StoryIcon/StoryIcon.tsx
- src/types/client/editProfile.client.ts
- src/types/client/follow.client.ts
- src/types/client/profile.client.ts
> ✨ Feat: 프로필 페이지, 프로필 편집 페이지 API 연동

- src/api/useUserAPI.ts
> 🚑 Fix: 잘못된 정보로 로그인 시 에러뜨는 버그 해결

- src/pages/FindPassword/FindPassword.tsx
- src/pages/SetPassword/SetPassword.tsx
- src/pages/SignUp/SignUp.tsx
비밀번호 찾기, 비밀번호 변경, 회원가입
input에 Enter 키 입력 이벤트 추가
> 🚑 Fix: 빌드 에러 해결

- src/api/useFeedAPI.ts
- src/components/AddModal/AddModal.style.tsx
- src/pages/Home/components/Comment/Comment.tsx
- src/pages/Home/components/CommentContent/CommentContent.tsx
- src/pages/Home/components/Feed/Feed.tsx
- src/pages/Home/components/FeedMenu/FeedMenu.tsx
- src/pages/Home/components/FeedModal/FeedModal.tsx
- src/pages/Home/components/Feeds/Feeds.tsx
- src/pages/Home/components/InnerCommentContent/InnerCommentContent.tsx
대댓글 바로 반영
좋아요 바로 반영
삭제 버튼 자신의 게시물 또는 댓글에서만 보이게 수정
> 🚑 Fix: 버그 수정

- src/pages/EditProfile/EditProfile.tsx
- src/pages/Profile/Profile.tsx
- src/types/client/profile.client.ts
> ✨ Feat: 프로필 페이지 동영상, 이미지 썸네일 구현

- src/api/useUserAPI.ts
- src/types/request/user.request.ts
로그아웃 시 쿠키 삭제되도록 하는 API 추가
회원가입 시 이메일 중복검사 API 추가
회원가입 시 닉네임 중복검사 API 추가
모든 중복검사를 통과해야 회원가입 요청이 보내짐
fixes: #8
> ✨ Feat: 로그아웃 API, 회원가입 중복검사 API 추가

- src/api/useAxios.ts
- src/api/useUserAPI.ts
- src/pages/FindPassword/FindPassword.tsx
- src/pages/SetPassword/SetPassword.tsx
비밀번호 변경을 위한 인증번호 이메일 전송 기능
인증번호가 일치하면 비밀번호 변경 페이지로 이동 후 비밀번호 변경
closed: #9 #17
> ✨ Feat: 비밀번호 변경 기능 추가

- src/api/useEditProfileAPI.ts
- src/api/useSearchAPI.ts
- src/pages/EditProfile/EditProfile.tsx
- src/pages/EditProfile/components/PrivateModal.tsx
- src/pages/EditProfile/components/PublicModal.tsx
- src/pages/EditProfile/components/Toggle.tsx
- src/pages/Profile/Profile.tsx
- src/pages/Profile/components/ProfileHeader.style.tsx
- src/pages/SearchTag/SearchTag.style.tsx
- src/pages/SearchTag/SearchTag.tsx
- src/pages/SearchTag/components/SearchHeader.style.tsx
- src/pages/SearchTag/components/SearchHeader.tsx
- src/recoil/editProfileState.ts
- src/types/client/search.client.ts
> James joe0830

- src/api/useFollowAPI.ts
- src/hooks/useTimeCalculate.tsx
- src/pages/Profile/components/FollowerModal.tsx
> ✨ Feat: 팔로워 기능 수정 및 API수정

- src/pages/Profile/components/ProfileBody.tsx
> ✨ Feat: 프로필 바디

- src/pages/EditProfile/EditProfile.tsx
> ✨ Feat: 프로필 편집 페이지 150 글자제한

- src/api/useEditProfileAPI.ts
> ✨ Feat:프로필 편집 페이지 Text null예외 처리
